### ISSUE TITLE
Onclick handler not working.

### ISSUE THREAD

**Issue by sivaramsi** [sagiegurari/angular-web-notification#11]
#### Problem Description
Onclick handler is not working when using this https://github.com/ttsvetko/HTML5-Desktop-Notifications, But when i use yours it works.
https://github.com/sagiegurari/HTML5-Desktop-Notifications

I couldn't find this in the npm registry can you upload that.

**Comment by sagiegurari** [comment]
I'm not going to upload my fork to npm. 
You might want to try to use github url as a dependency.  Might work for you.

**Comment by sivaramsi** [comment]
No problem i got that from bower :)....
