### ISSUE TITLE
Notification not appearing, but code runs fine

### ISSUE THREAD

**Issue by Chrono73** [sagiegurari/angular-web-notification#12]
#### Problem Description

Hi,
I've been trying to use angular-web-notification to create a small service containing various functions that I can call in my own functions, as well as export to other apps. Thus, I didn't create a new directive like you did in the README's example, but a new service, and just copy/pasted your code to see if it worked, after including the necessary scripts in the html DOM.

When I call the service's function, no notification shows up, but no error gets thrown.I know that my browser is compatible since it works with your Plunker example, and I can't figure out what the problem is. I have no errors in my console whatsoever, and the rest of the app runs normally, bar from the notification.

#### Code Example

````js
myApp.service('notify', ['webNotification', function(webNotification) {
    this.fire = function() {
        webNotification.showNotification('Example Notification', {
            body: 'Notification Text...',
            onClick: function onNotificationClicked() {
                console.log('Notification clicked.');
            },
        autoClose: 4000 //auto close the notification after 4 seconds (you can manually close it via hide function)
        }, function onShow(error, hide) {
            console.log(arguments);
            if (error) {
                window.alert('Unable to show notification: ' + error.message);
                console.log(error.message);
            } else {
                window.alert('Notification shown!');
                setTimeout(function hideNotification() {
                    hide();
                }, 5000);
            }
        });
    } 
}]);
````

Any ideas ?

Thanks in advance.

**Comment by sagiegurari** [comment]
hard to say actually without more code and console output.
few things come to mind:
* permissions? permissions are per site you are visiting, so maybe you did deny once and it sticks so you need to clear your decision in the browser settings (by the way which browser?)
* any chance you put few more console.log there? maybe at start of fire function? could be that the fire function is not even called.
* just to avoid conflict (although i'm sure i'm wrong here), there is a global called notify (window.notify) because of one of the imports, and your service is also called notify so when you inject it, it should take yours, but if you didn't inject correctly you might be using the global directly which doesn't have fire function defined.

**Comment by Chrono73** [comment]
Thanks for taking the time to answer.

I'm using Safari 9.0.3 at the moment. I've just checked the things you mentioned:

- I've changed the service name, just to be sure, even though as you predicted that didn't change anything. At least I'm aware of it now.
- I'm 100% sure the Fire function is called, since each time I want to have the notification show, the ````window.alert('Notification shown!');````pops up. The onShow function is called with arguments null and  function hideNotification() { notification.close(); }.
- webNotification.allowRequest is set to true before I call showNotification, and permissionGranted is also set to true after the first showNotification call. Subsequent showNotification calls don't change anything. That's strange because when I checked my browser's notification settings, my app wasn't listed as part of the websites that asked for permission to notify.

I could send you the rest of the code, but it's irrelevant to the question, it's just some functions to connect to a database and process data. I haven't changed anything in my .html yet, besides adding the scripts. I've got no console output either, except the ````console.log(arguments);```` that I used above, and the two console.log that I added to check for allowRequest & permissionGranted.

**Comment by sagiegurari** [comment]
if you see the alert notification shown than yes the.code runs and looks like everything should be ok.
if the plunker works than browser is supported as you wrote before.
the only difference I see is that you didn't provide an icon which shouldn't be mandatory but I don't have a Mac to test safari to see if it must have it.

**Comment by Chrono73** [comment]
I'm going to try poking into your code a bit to see if I spot something, since adding an icon didn't change anything. If I find something I'll post it here.

**Comment by sagiegurari** [comment]
can you check safari notification preferences in your browser?
https://support.apple.com/kb/PH21445?locale=en_US&viewlocale=en_US
Just to check that everything is ok for the domain you are using to test your application.

**Comment by Chrono73** [comment]
That's what I said, my app doesn't appear in the list of websites that asked for permission, in the notification preferences panel.

I tried just downloading the Plunker example as it is, and not changing a single thing. Just like last time, no error, but it doesn't work. I'm starting to think that Safari doesn't expect notifications from a local app, only from distant websites.

I'll try with Firefox, or by hosting a quick Heroku app to check that theory.

**Comment by sagiegurari** [comment]
ok, keep me updated.

**Comment by Chrono73** [comment]
It works with Firefox. It appears that it's indeed Safari not listening for notifications from local apps. I'll try with Heroku, to check if it works with distant websites.

**Comment by sagiegurari** [comment]
sure
