### ISSUE TITLE
Docs mention HTML5-Desktop-Notifications2

### ISSUE THREAD

**Issue by amit777** [sagiegurari/angular-web-notification#13]
I noticed in the documentation that you are referencing "HTML5-Desktop-Notifications2/desktop-notify.js"  Is there a reason that you using HTML5-Desktop-Notifications2 vs HTML5-Desktop-Notifications?  It seems like HTML5-Desktop-Notifications2 is a fork that you made.

**Comment by sagiegurari** [comment]
had to fork it to provide access to some functionality. you can compare my fork and the original repo.

**Comment by amit777** [comment]
Got it.. thanks.  I noticed this when I used an old version of this module.. is using your fork still required for your angular module?  If so, I will switch to yours (though it's not listed in npm).

**Comment by sagiegurari** [comment]
still needed and I'm pretty sure I told you several months ago that I'm not going to publish the fork via npm.
it is however published via bower.

**Comment by amit777** [comment]
I did a quick check of the forks here: https://github.com/sagiegurari/HTML5-Desktop-Notifications/network

it looks like the main project's master branch shares a recent common commit from you.  It's just missing your latest commit.  So seems like the main project may work fine.  I've done a little a testing, and it looks ok.

**Comment by sagiegurari** [comment]
I'm not sure why not to use my fork as I defined in bower.json and docs, I fail to see the issue.
the fork was done to support the onclick, but if you don't need that than you can use the original repo but still not sure why you want to do that.
I'm closing this case unless you actually have something more meaningful to add.

**Comment by sagiegurari** [comment]
seems I confused you with some else that wanted this in nom, in issue #10
anyhow, I only publish my work (not forks) via npm so that's why it is not there.
if you must use npm you can use git url in your package.json
