### ISSUE TITLE
Request for simplified method

### ISSUE THREAD

**Issue by kdekooter** [sagiegurari/angular-web-notification#14]
It would be really nice to be able to trigger a notification with a simplified method, without the callback clutter. Something like `webNotification.info(title, body)`.

**Comment by sagiegurari** [comment]
but if there is an error showing the notification, you won't know about it.
Is that ok by you?

**Comment by sagiegurari** [comment]
Ok, so I implemented the callback to be optional.
You can now do:

````js
webNotification.showNotification('Example Notification', {body: 'Notification Text...'});
````

The second param is still an object since you want only body, but others might want icon/click handler/so on...

**Comment by kdekooter** [comment]
I would prefer to check if the notification machinery is working on startup of the application and not have to worry about that everywhere a notification is triggered.

This is going to work for me. Thanks for the swift response!

**Comment by kdekooter** [comment]
I noticed that if you don't set the `icon` property the notification does not show.
