### ISSUE TITLE
Use favicon.ico as default icon 

### ISSUE THREAD

**Issue by kdekooter** [sagiegurari/angular-web-notification#15]
At the moment the `icon` property has to be set for the notification to show. A sensible default value would be `favicon.ico`.

**Comment by sagiegurari** [comment]
Nice idea. I'll take a look at that but will only have time next week.

**Comment by sagiegurari** [comment]
check version 1.0.6 which has your requested default.
Hope it works good for you.

````js
//defaults the notification icon to the website favicon.ico
if (!options.icon) {
  options.icon = document.location.protocol + '//' + document.location.host + '/favicon.ico';
}
````

**Comment by kdekooter** [comment]
Excellent. Thanks!
