### ISSUE TITLE
Having probing in inject the angular-web-notification

### ISSUE THREAD

**Issue by GitChethan** [sagiegurari/angular-web-notification#16]
I am increasing the auto close time to 20 sec, But still notifications are closing to 10 or 11 sec default, Do you know is there any OS related settings.

**Comment by sagiegurari** [comment]
Check the docs of your specific browser.
Each browser might have different limitations enforced on web notifications.

**Comment by sagiegurari** [comment]
I'm closing this issue due to lack of feedback.
