### ISSUE TITLE
autoClose is always enabled

### ISSUE THREAD

**Issue by agustincassanioe** [sagiegurari/angular-web-notification#19]
No matter what value or no value at all you assign to autoClose options property, the notification is always vanishing after some seconds (seems to be 15 by default).
#### Problem Description
We need to close the notification only from two possible ways, from the x on the top right corner or after clicking on it (notification body). From the issue: "Hide notification on click #7" (https://github.com/sagiegurari/angular-web-notification/issues/7) we got how to make it work and it is working perfectly but when you do not click either the text or the x, we want the notification to stay there permanently.

Based on the documentation, we have the following:

[options.autoClose] -> number -> Auto closes the notification after the provided amount of millies (0 or undefined for no auto close)

But this is not working for us.

This is the code we are using:

          var hideNotification;

          webNotification.showNotification('Title', {
            body: 'My body',
            icon: 'myImage.ico',
            onClick: function onNotificationClicked() {
              ...
              // manually hide the notification after clicking on it
              if (hideNotification) {
                hideNotification();
              }
            }
          }, function onShow(error, hide) {
            if (error) {
              window.alert('Unable to show notification: ' + error.message);
            } else {
              hideNotification = hide;
            }
          });
        });

We are getting no error at all but no matter the value of autoClose property, we have tried everything, setting it up, assigning it to 0 or values higher then 15000 but the notification always vanish after a short period of time.

Is there a way to avoid this behavior?

Thanks a lot in advance for you help!

Best regards.

**Comment by sagiegurari** [comment]
The browser enforces that. Check property requireInteraction=true to ensure that.
You can read about it in #9

**Comment by agustincassanioe** [comment]
Thanks a lot for your quick response! I am using Chrome Version 53.0.2785.143 (64-bit) and no luck for me even using several options such as:

1 ) Before invoking showNotification method

        // force notification to be shown until user clicks on it
        webNotification.requireInteraction = true;

2) Adding the property to the showNotification options object

          var hideNotification;
          webNotification.showNotification('Title', {
            body: 'My Notification Body',
            icon: 'path/to/my/icon.ico',
            onClick: function onNotificationClicked() {
             ...
              // manually hide the notification after clicking on it
              if (hideNotification) {
                hideNotification();
              }
            },
            requireInteraction: true
          }, function onShow(error, hide) {
            if (error) {
              window.alert('Unable to show notification: ' + error.message);
            } else {
              hideNotification = hide;
            }
          });

And of course setting and omitting autoClose property.

Am I doing something wrong or is just something related to the browser?

Thanks again for your help!

Best regards.

**Comment by sagiegurari** [comment]
Its because of the browser I'm afraid.
I have seen many apis change behavior due to abuse.
Strange the persistent flag didn't work.
Also keep in mind of a scenario that you have more than 3 notifications, in which case chrome removes the old ones and notifications can come from different web sites.

**Comment by sagiegurari** [comment]
closing this one.
if there is anything I can help with please reopen or open a new case.
