### ISSUE TITLE
 HTML5-Desktop-Notifications 'tag' feature

### ISSUE THREAD

**Issue by amit777** [sagiegurari/angular-web-notification#2]
Is there a way to use the 'tag' parameter of  HTML5-Desktop-Notifications?  If I have multiple windows open that all have websocket connections, I would like to prevent the same notification from showing up multiple times.

**Comment by sagiegurari** [comment]
never tested it, but basically you can pass it in the options object:
https://github.com/sagiegurari/angular-web-notification/blob/master/docs/api.md#webNotification.showNotification

tell me if it works for you.

**Comment by sagiegurari** [comment]
I'm closing this one as I believe it is supported just fine.
If there is any problem please just reopen the issue and I'll handle.
