### ISSUE TITLE
Not installing from bower

### ISSUE THREAD

**Issue by gerardogrimaldi** [sagiegurari/angular-web-notification#21]
#### Not installing from bower
$ bower install angular-web-notification --save

#### After executing that i get...
bower HTML5-Desktop-Notifications2#1.0.1           cached https://github.com/sagiegurari/HTML5-Desktop-Notifications.git#1.0.1
bower HTML5-Desktop-Notifications2#1.0.1         validate 1.0.1 against https://github.com/sagiegurari/HTML5-Desktop-Notifications.git#1.0.1
bower angular-web-notification#*                   cached https://github.com/sagiegurari/angular-web-notification.git#1.0.21
bower angular-web-notification#*                 validate 1.0.21 against https://github.com/sagiegurari/angular-web-notification.git#*
bower HTML5-Desktop-Notifications2#1.0.1     ENORESTARGET No tag found that was able to satisfy 1.0.1

#### Any solution?

**Comment by sagiegurari** [comment]
You are using an old version of this library.
Please upgrade to the latest version and retry.

**Comment by gerardogrimaldi** [comment]
Thanks, i delete the old library from the project, that was the error. It's working again.

**Comment by sagiegurari** [comment]
👍 enjoy
