### ISSUE TITLE
Cannot read property 'showNotification' of undefined

### ISSUE THREAD

**Issue by garymartin87** [sagiegurari/angular-web-notification#22]
Hello, since last update (v1.2.4), my custom service where I use angular-web-notification:

```
(function () {
    'use strict';

    angular
        .module('doc24App-medico')
        .factory('desktopNotification', desktopNotification);

    desktopNotification.$inject = ['webNotification', 'ngAudio'];

    function desktopNotification(webNotification, ngAudio) {
        var desktopNotification = this;

        desktopNotification.soundFile = '../audio/sms-alert-3-daniel_simon.mp3';
        desktopNotification.titleDefault = 'defaultTitle';
        desktopNotification.autoCloseDefault = 5000;
        desktopNotification.icon = '../app-medico/images/logo_small.png';

        desktopNotification.fireDesktopNotification = function(message, onClick, title, autoClose){
            if (!title){
                title = desktopNotification.titleDefault;
            }
            if (!autoClose){
                autoClose = desktopNotification.autoCloseDefault;
            }
            webNotification.showNotification(title, {
                body: message,
                icon: desktopNotification.icon,
                onClick: function onNotificationClicked() {
                    onClick();
                },
                autoClose: autoClose //(you can manually close it via hide function)
            }, function onShow(error, hide) {
                if (error) {
                    // window.alert('Unable to show notification: ' + error.message);
                } else {
                    // console.log('Notification Shown.');
                    setTimeout(function hideNotification() {
                        // console.log('Hiding notification....');
                        hide(); //manually close the notification (you can skip this if you use the autoClose option)
                    }, autoClose);
                }
            });

            var audioObject = ngAudio.load(desktopNotification.soundFile);
            audioObject.play();
        };

        return {

            fireDesktopNotification: function(message, onClick, title, autoClose) {
                return desktopNotification.fireDesktopNotification(message, onClick, title, autoClose);
            }

        }
    }
})();
```

 it's showing the following error:

TypeError: Cannot read property 'showNotification' of undefined
    at Object.onCreateService (http://doc24.local/app-medico/js/dist/vendor.js:9328:50)
    at Object.invoke (http://doc24.local/app-medico/js/dist/vendor.js:43:175)
    at Object.$get (http://doc24.local/app-medico/js/dist/vendor.js:40:311)
    at Object.invoke (http://doc24.local/app-medico/js/dist/vendor.js:43:175)
    at http://doc24.local/app-medico/js/dist/vendor.js:44:486
    at d (http://doc24.local/app-medico/js/dist/vendor.js:42:92)
    at e (http://doc24.local/app-medico/js/dist/vendor.js:42:333)
    at Object.invoke (http://doc24.local/app-medico/js/dist/vendor.js:42:418)
    at Object.$get (http://doc24.local/app-medico/js/dist/vendor.js:40:311)
    at Object.invoke (http://doc24.local/app-medico/js/dist/vendor.js:43:175)
    at http://doc24.local/app-medico/js/dist/vendor.js:44:486
    at d (http://doc24.local/app-medico/js/dist/vendor.js:42:92)
    at e (http://doc24.local/app-medico/js/dist/vendor.js:42:333)
    at Object.instantiate (http://doc24.local/app-medico/js/dist/vendor.js:43:244)
    at http://doc24.local/app-medico/js/dist/vendor.js:93:141
    at Object.<anonymous> (http://doc24.local/app-medico/js/dist/vendor.js:353:24299) <div ui-view="" class="ng-scope" data-ng-animate="1">
(anonymous) @ angular.min.js:122
f @ angular-loggly-logger.min.js:1
(anonymous) @ angular.min.js:94
(anonymous) @ angulartics.min.js:32
ta @ angular.min.js:84
n @ angular.min.js:69
g @ angular.min.js:60
(anonymous) @ angular.min.js:60
(anonymous) @ angular.min.js:65
l @ angular-ui-router.min.js:7
(anonymous) @ angular-ui-router.min.js:7
$broadcast @ angular.min.js:150
(anonymous) @ angular-ui-router.min.js:7
(anonymous) @ angular.min.js:133
$eval @ angular.min.js:147
$digest @ angular.min.js:144
$apply @ angular.min.js:148
l @ angular.min.js:101
t.onload @ angular.min.js:106

looking forward to any updates.

Thks!!

**Comment by sagiegurari** [comment]
The new version adds an additional dependency: simple-web-notification/web-notification.js
The docs show an example of that so you can look there and also the example page was updated with that if you want to see a live example.
Basically it means you need to
1. run bower install to get the latest dependency
2. include that dependency in your html or bundling process

**Comment by garymartin87** [comment]
It's working!

Thks very much!!!

**Comment by sagiegurari** [comment]
good to hear 👍 
the whole purpose was to enable to use the api I wrote outside of angular so I split it.
