### ISSUE TITLE
Prevent multiple notification on multiple opened tabs

### ISSUE THREAD

**Issue by fott1** [sagiegurari/angular-web-notification#24]
I suggest adding the 'tag' key which it prevents firing multiple notification with the same tag. Applies perfectly when opening multiple tabs and we need 1 notification

````js
body: data.msg,
tag : 'onetime-notification',
````
 
Tested in Chrome only.

**Comment by sagiegurari** [comment]
See #2 
it is already supported.

**Comment by sagiegurari** [comment]
Closing this one. If it doesn't work you can reopen.

**Comment by c3p0upgini** [comment]
Tag doesn't work in Safari
