### ISSUE TITLE
How we can use it?

### ISSUE THREAD

**Issue by narendrasinghrathore** [sagiegurari/angular-web-notification#26]
Hi there, i need some help on this angular-web-notification.

Let me first explain it, i am using the code below which register to service worker and i get push notification in chrome  i.e  sw.js( name of file )
    `use strict';

    const applicationServerPublicKey = 'key';
    function urlB64ToUint8Array(base64String) {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding)
        .replace(/\-/g, '+')
        .replace(/_/g, '/');

    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);

    for (var i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
    }
     return outputArray;
    }

    self.addEventListener('push', function(event) {
    console.log('[Service Worker] Push Received.');
    // console.log(`[Service Worker] Push had this data: "${event.data.text()}"`);

    console.log(event.data);
    console.log(event.data.json());
    console.log(typeof (event.data.json()));
    console.log(event);
    const title = 'xyz';
    const options = {
    body: 'Message Received \n ' + event.data.json().message,
    icon: 'images/icon.png',
    // badge: 'images/badge.png',
    data : event.data.json()
    };

    event.waitUntil(self.registration.showNotification(title, options));
    });

    self.addEventListener('notificationclick', function(event) {

    console.log('[Service Worker] Notification click Received.');

    event.notification.close();

    event.waitUntil(
        clients.openWindow('url');
    );
    });

    self.addEventListener('pushsubscriptionchange', function(event) {
    console.log('[Service Worker]: \'pushsubscriptionchange\' event fired.');
    const applicationServerKey = urlB64ToUint8Array(applicationServerPublicKey);
     event.waitUntil(
        self.registration.pushManager.subscribe({
                userVisibleOnly: true,
                applicationServerKey: applicationServerKey
            })
            .then(function(newSubscription) {
                console.log('[Service Worker] New subscription: ', newSubscription);
            })
    );
    });`

    `if ('serviceWorker' in navigator && 'PushManager' in window) {

    navigator.serviceWorker.register('../sw.js')
    .then(function (swReg) {
                    onServiceWorkerReady(swReg);

    swRegistration.pushManager.subscribe({
    userVisibleOnly: true,
    applicationServerKey: applicationServerKey
    })
    .then(function (subscription) {
     updateSubscriptionOnServer(subscription);
    isSubscribed = true;
    //updateBtn();
    })
    .catch(function (err) {
    console.log('Failed to subscribe the user: ', err);
    //         updateBtn();
    //     });
    })
    .catch(function (error) {
    console.error('Service Worker Error', error);
    });
    } else {
    console.warn('Push messaging is not supported');
    //pushButton.textContent = 'Push Not Supported';
    }
`

What i need is that when i get notification from web-server , i also need my angular-app to perform some action.
By using the above, i am not able catch any event or maybe i don't know how to do that.
Links i try to figured out
1) [https://github.com/sagiegurari/angular-web-notification](url)
2) [ https://github.com/jmsanpascual/angular-desktop-notification](url)
3) [https://github.com/matiboy/angular-browser-push-notifications](url)

I cannot exactly figure out, how i suppose to use your lib that help me to **perform action in angular-app** whenever i push notification or service worker get push notification.

Thank you,

**Comment by sagiegurari** [comment]
Sorry but i don't understand what is the question or the issue

**Comment by narendrasinghrathore** [comment]
Thanks for reply. What i need is that,

**For-eg:** when we use $on or $watch, it just notify us real-time that event is fire or variable value changed.

I have node.js server with help of [https://www.npmjs.com/package/web-push](web-push) from where i get notification to service worker in chrome or firefox. 
It just display web-notification even if web browser is minimized. That's all ok, fine.


Now i have some angularjs code , basically app. So i need to perform some http call or any action when i get **web-notification** in browser.  How can i get that. How can i broadcast or fire some event and notify my angular-app that do some action.

**I read your lib it displays web-notification on click button as shown in example/demo,  and i need to perform same when get push event from server. ** This code below called log when receive push notification from server. 

    `self.addEventListener('push', function(event) {
    console.log('[Service Worker] Push Received.');
 
    const title = 'YummZ';
    const options = {
        body: 'Message Received \n ' + event.data.json().message,
        icon: 'images/icon.png',
        // badge: 'images/badge.png',
        data : event.data.json()
     };

    event.waitUntil(self.registration.showNotification(title, options));
    });
`

Sorry if it still confuses you. I read many blog but not able to find any solution.
Please let me know
Thank you

**Comment by sagiegurari** [comment]
So if I understand correctly (might not, hard to understand the flow from your question), 
1. service worker gets some event and than shows web notification
2. you want angular app to do some http call when service worker shows a notification
am I right?

**Comment by narendrasinghrathore** [comment]
@sagiegurari perfectly right.

**Comment by sagiegurari** [comment]
so... why not instead, just send a message from the service worker to the angular app to do that http call? why listen to the web notification?

https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/postMessage

**Comment by narendrasinghrathore** [comment]
@sagieguari i am trying this


            var angularClient;
            self.addEventListener('message', event => {
                         // if message is a "ping" string, 
                        // we store the client sent the message into angularClient variable
                        if (event.data == "ping") { 
                        angularClient = event.source;  
                        }
            });

            self.addEventListener('push', function(event) {
                        console.log('[Service Worker] Push Received.',event);
                        // console.log(`[Service Worker] Push had this data: "${event.data.text()}"`);

                        console.log(event.data);
                        console.log(event.data.json());
                        console.log(typeof (event.data.json()));

                        angularEvent.postMessage("xyz",event.data.json());


                        const title = 'xyz';
                        const options = {
                        body: 'Message Received \n ' + event.data.json().message,
                         icon: 'images/icon.png',
                        // badge: 'images/badge.png',
                        data : event.data.json()
                        };

             event.waitUntil(self.registration.showNotification(title, options));
            });


`

In angular app


            window.addEventListener('xyz',function(e) {

                console.log('asdsa000');
            });
`


No success.
**Getting error : cannot read property postMessage of undefined.**

found this but not helpful [https://stackoverflow.com/questions/37834164/to-communicate-service-worker-with-angular-js-controller](url)
Need help..
Thank you.

**Comment by sagiegurari** [comment]
ok.... I have to admit that it is not related to this project and therefore I would prefer that it would be answered in a different forum.

**Comment by narendrasinghrathore** [comment]
No issues.
In case if you have something feel free to write here, it will help me.
You can close it if you want.
Thank you very much.
