### ISSUE TITLE
Action buttons ?

### ISSUE THREAD

**Issue by Ercetei** [sagiegurari/angular-web-notification#27]
#### Problem Description
Hello!
Is there any way to handle action buttons ? I tried but receive this error.
Thanks!

#### Code Example

````js
webNotification.showNotification(notification.title, {
                body: notification.body,
                icon: notification.icon,
                actions: [
                    {action: 'dismiss', title: 'dismiss'},
                    {action: 'later', title: 'see later'}],
                autoClose: 0
            }, function onShow(error, hide) {
                if (error) {
                    window.alert('Unable to show notification: ' + error.message);
                } 
            });
````

#### Error Stack/Info (if any)
`Uncaught TypeError: Failed to construct 'Notification': Actions are only supported for persistent notifications shown using ServiceWorkerRegistration.showNotification().`

**Comment by sagiegurari** [comment]
Currently showing notifications via service workers is not supported.
I'll keep this one open and investigate, but this API is not fully supported yet by most browsers.

**Comment by sagiegurari** [comment]
Sorry for taking so long but the API now supports service worker webnotifications.
The support actually comes from the internal library [simple-web-notification](https://github.com/sagiegurari/simple-web-notification), so here I just [documented it](https://github.com/sagiegurari/angular-web-notification#usage)

**Comment by sagiegurari** [comment]
Closing due to lack of feedback

**Comment by Ercetei** [comment]
Hey! Thanks for the update; it seems to work great with service worker now. 
I tried on Chrome & Firefox - Firefox doesn't support actions buttons for what i could see - I didn't have any problem for now, i'll keep you informed if there is any. 
Thanks again!
