### ISSUE TITLE
Handler click notify?

### ISSUE THREAD

**Issue by highfeed** [sagiegurari/angular-web-notification#3]
Hi.

How to handle a click on the notification?

**Comment by sagiegurari** [comment]
You are right, its missing so just added support for it.
Once the build finishes I'll publish a new release.
Basically it will be another option when you show the notification:

````js
webNotification.showNotification('Example Notification', {
  body: 'Notification Text...',
  icon: 'my-icon.ico',
  onClick: function onNotificationClicked() {
    console.log('Notification clicked.');
  }
}, function onShow(error, hide) {
````

**Comment by sagiegurari** [comment]
Done and published (bower version 0.0.30)
You can give it a try.
Please delete the old HTML5-Desktop-Notifications as I forked it to add the access to the browser notification object so now the bower.json points to my forked repo.

**Comment by sagiegurari** [comment]
I updated HTML5-Desktop-Notifications and published via bower with name: HTML5-Desktop-Notifications2
So now please make sure to update your HTML include to HTML5-Desktop-Notifications2

**Comment by highfeed** [comment]
Thanks!
