### ISSUE TITLE
Notifications not showing up

### ISSUE THREAD

**Issue by oktay89** [sagiegurari/angular-web-notification#34]
### Describe The Bug
I can't get the notifications to show up. Neither in my code or demo.
![image](https://user-images.githubusercontent.com/5344698/96238760-1e72f880-0f9f-11eb-943c-01344fb6cb3c.png)

### To Reproduce
Go to the demo and click on show notification

### Error Stack
Unable to show notification: Unable to find notification.
```console
```

### Code Sample
https://sagiegurari.github.io/angular-web-notification/
```js
```

**Comment by sagiegurari** [comment]
@oktay89 just checked it. I also use chrome desktop as you and seems to work fine.
so i'm not sure how to reproduce the issue.

**Comment by oktay89** [comment]
I use Chrome Version 86.0.4240.75 (Oficial Build) (64-Bit) with Windows 10 Pro (1809) OS. 
Also tried to open the demo seite in incognito mode, so no extensions block/change anything

**Comment by sagiegurari** [comment]
i used latest chrome as well on win 10.
notifications won't work in incognito because you can't get permission approval in incognito.
same goes for any js api that requires permissions.
