### ISSUE TITLE
Gulp uglify issue

### ISSUE THREAD

**Issue by Mohini89** [sagiegurari/angular-web-notification#35]
This plugin works fine without gulp uglify code but when it is run for production build it throws an error.

"[Uglify] Error in plugin 'gulp-uglify'
Unexpected token: name (tagCounter)"

Please guide.

**Comment by sagiegurari** [comment]
tagCounter is defined in the function level and used internally. feels like uglify bug, but could be wrong.

https://github.com/sagiegurari/simple-web-notification/blob/fb94ff835c97937c567f32235003494a5955dcf4/web-notification.js#L73

**Comment by sagiegurari** [comment]
@Mohini89 did you by any chance created an issue for gulp uglify with your setup?
because it feels like an issue there. i do know this project has been used with various minifiers at the past.
