### ISSUE TITLE
onClick handler not getting called when showing from controller

### ISSUE THREAD

**Issue by nstohler** [sagiegurari/angular-web-notification#4]
Hi,
I'm calling this in one of my controllers functions upon the arrival of a new item that the user wants to be notified about:

    webNotification.showNotification(item.name, {
    	body: bodyText,
    	icon: String.format('images/{0}.jpg', item.name),
    	onClick: function onNotificationClicked() {
  		showInfoDialog(item);
    		window.console.log('Notification clicked.');
    	},	
    	autoClose: watchListNotificationAutoCloseTime, //auto close the notification after 5 minutes (you manually close it via hide function)
    }, function onShow(error, hide) {
    	if (error) {
    		window.alert('Unable to show notification: ' + error.message);
    	} else {
    		$log.log('Notification Shown.');
    	}
    });

Now, the notification pops up. But when I click on it, I see no console log and my controller function also does not get called. What am I doing wrong? I took the code from your plunkr sample.

**Comment by sagiegurari** [comment]
what is showInfoDialog? you sure it doesn't have any issue?
did you try only console.log? like in the plunker which works ok.

**Comment by nstohler** [comment]
showInfoDialog is just another function in the controller. And yes, when I only put console.log, it does not work either. 
I'll try to reproduce the problem in a plunk

**Comment by nstohler** [comment]
My plunk version worked of course! 

But now I found the problem: When getting the files, I followed the link to "HTML5-Desktop-Notifications" on your instruction page and got "desktop-notify.js" and "desktop-notify.min.js" there ("https://raw.githubusercontent.com/ttsvetko/HTML5-Desktop-Notifications/master/desktop-notify.js"). 

It seems like they work for displaying the notification, but for the click event. So I analyzed your plunk and found that I had to use "https://rawgit.com/sagiegurari/HTML5-Desktop-Notifications/master/desktop-notify.js". Maybe include that file into the angular-web-notification package as well? 

(I'm not using bower yet (maybe I should), so I dont know if there's a problem with that too. I just donwloaded the github zip and installed the files manually). 

[I wanted to add my plunk here, but it looks like plunker is currently not reachable for me and I cannot save. I will try again tomorrow]

**Comment by sagiegurari** [comment]
My bower points to the right version. Also the examples.
The readme points to the original repo only for documentation.
If you use bower it will work fine, or you can use bower one time to just download the files instead of doing it manually.

**Comment by nstohler** [comment]
Ok, thanks. Probably I should get into using bower then to avoid these kinds of problems. 

Thanks for the help! Great component!

Here my plunk, maybe it helps someone else:
http://plnkr.co/edit/bnidDoRgi1wE2q7mJqYn?p=preview

**Comment by erwinkramer** [comment]
Just to note: the only difference is that the working `desktop-notify.js` file has the line `webNotification: notification,` added just after the beginning of the return block at line 101.

**Comment by sagiegurari** [comment]
yap. didn't want to fork just for that small change but the original repo seems kind of dead so had to.
