### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by iBasit** [sagiegurari/angular-web-notification#5]
Is there functions to check if browser support web notifications?

and also is there function to request permission if user does not have permission yet, but show this link only if web browser supports notifications.

**Comment by sagiegurari** [comment]
The showNotification function will automatically check and ask (if needed) for permissions for you, so you don't really need to mess with that (simplifies things).
as to check if supports or not, I don't have it, but if you call the showNotification and there is any issue, the callback will provide an error and than you can fallback to another custom solution.

**Comment by iBasit** [comment]
I don't want to enforce the permission box to open. It is already doing on my site for geolocation. So I want user to select desktop notification then start showing, else dont show.

**Comment by sagiegurari** [comment]
See https://github.com/sagiegurari/angular-web-notification/blob/master/docs/api.md#webNotification.allowRequest
Basically if you set it to false, it will not automatically request permissions.
Does that solve your issue?

**Comment by iBasit** [comment]
Partially. but thanks
