### ISSUE TITLE
get webnotifications permissions

### ISSUE THREAD

**Issue by amit777** [sagiegurari/angular-web-notification#6]
It would be great if we could use the service to get the current state.  Right now I'm using the global window.notify object.

**Comment by sagiegurari** [comment]
Just a question, but why do you need it?
I built the API in a way that you don't need to mess with that, so maybe I'm missing something.

**Comment by amit777** [comment]
I wanted to have small indicators in my UI about the status.. more for diagnostic purposes.

**Comment by sagiegurari** [comment]
ok, I'll try to add that this week.

**Comment by sagiegurari** [comment]
Added webNotification.permissionGranted attribute (boolean), hope that helps.

https://github.com/sagiegurari/angular-web-notification/blob/master/docs/api.md#webNotification.permissionGranted

I don't want to give the actual permission name and prefer to have a true/false flag.

pushed with version: 0.0.65
