### ISSUE TITLE
Persistent Web Notifications

### ISSUE THREAD

**Issue by smirciat** [sagiegurari/angular-web-notification#9]
Anyone have any resource to suggest for a persistent notification?  I have figured out that I need a Service Worker to do that with the Notifications API, but I'm not sure how to proceed, and also not sure if it would be consistent with this repository.  Thanks for any help with this.

**Comment by sagiegurari** [comment]
not sure I fully understand what you are asking, but i'm not sure that angular can be used in a worker process as worker doesn't have dom access.
I could be wrong.
What exactly are you trying to do?

**Comment by smirciat** [comment]
Thanks for replying on this.  I have the desktop notification working well with this repo, thanks very much for it!  What I would like to do is have it remain open until a user brings the app page back into focus  in case they are away.  As it is, no matter how long I set the notification for, it disappears after 15 seconds when fired from Chrome.  A quick bit of research indicates this is the expected behavior for a non-persistent HTML5 notification.  I am still exploring this topic from a non-angular direction, from your initial answer that may be my direction.  Thanks again!

**Comment by sagiegurari** [comment]
Did you try putting 0?
For me notifications got stuck because of it, which is what you want.
And I only use chrome.
Strange it would not work anymore.
Anyway, if it doesn't (probably wont based on your detailed answer), tell me and I will also investigate it.

**Comment by smirciat** [comment]
Thanks again for the reply.  AutoClose: 0 gives me the same ~15 second notification with Chrome.  I also tried without the option entirely, still limited to ~15 sec.  The change from your previous experience may be from a Chrome update.  Would love to hear any additional ideas.

**Comment by sagiegurari** [comment]
Can you try option requireInteraction=true?

**Comment by smirciat** [comment]
I actually just tried that as you typed it.  It works on Firefox, but does not affect Chrome.  Interesting, might get implemented soon as it seems like a new part of the API

**Comment by sagiegurari** [comment]
I actually saw it in chrome API docs 
Anyhow I think that is the solution you need even if not fully supported yet. That and not providing close time to support old chrome versions.
Should give you somewhat a solution for most use cases.
Nothing is perfect.

**Comment by smirciat** [comment]
Now I see requireInteraction is supposed to be implemented in Chrome 47, I might be missing something in my implementation, I'll keep at it
